In [1]:
import pandas as pd
import re

In [2]:
# File processing
from pathlib import Path
import tarfile

In [3]:
base_dir = Path("../")
parsed_data_dir = base_dir / "parsed_data"
ref_data_dir = Path("../../reference_files/")

In [4]:
data_dir = base_dir / "raw_data"

# Values

In [5]:
SERIES_ACCESSION = "GSE60143"

In [17]:
sample_df = pd.read_csv(parsed_data_dir / "sample_info.tsv", sep="\t")
print(sample_df.shape)
sample_df.head()

(568, 13)

,gene id,dna source,summary,taxon,protein,protein family,protein affinity tag,expression system,replicate,title,accession,common title,file_name
0,AT1G01060,col,young leaf,Arabidopsis thaliana,LHY1,MYBrelated,Halo,tnt,a,MYBrelated_tnt.LHY1_col_a,GSM1925527,MYBrelated_tnt.LHY1_col_a,../raw_data/GSE60141/GSM1925527_DAPSeq-MYBrela...
1,AT1G01060,colamp,young leaf,Arabidopsis thaliana,LHY1,MYBrelated,Halo,tnt,a,MYBrelated_tnt.LHY1_colamp_a,GSM1925526,MYBrelated_tnt.LHY1_colamp_a,../raw_data/GSE60141/GSM1925526_DAPSeq-MYBrela...
2,AT1G01250,col,young leaf,Arabidopsis thaliana,AT1G01250,AP2EREBP,Halo,tnt,a,AP2EREBP_tnt.AT1G01250_col_a,GSM1925016,AP2EREBP_tnt.AT1G01250_col_a,../raw_data/GSE60141/GSM1925016_DAPSeq-AP2EREB...
3,AT1G01720,col,young leaf,Arabidopsis thaliana,ATAF1,NAC,Halo,tnt,a,NAC_tnt.ATAF1_col_a,GSM1925578,NAC_tnt.ATAF1_col_a,../raw_data/GSE60141/GSM1925578_DAPSeq-NAC_tnt...
4,AT1G02230,col,young leaf,Arabidopsis thaliana,ANAC004,NAC,Halo,tnt,a,NAC_tnt.ANAC004_col_a,GSM1925535,NAC_tnt.ANAC004_col_a,../raw_data/GSE60141/GSM1925535_DAPSeq-NAC_tnt...

In [19]:
dapseq_file_names = set(sample_df["file_name"])
len(dapseq_file_names)

568

In [15]:
sample_df.head()

,Accession,title,summary,gene id,file_name
0,GSM1925639,SBP_tnt.SPL9_col_a,young leaf,AT2G42200,GSM1925639_DAPSeq-SBP_tnt-SPL9_col_a-chr1-5_GE...
1,GSM1925722,WRKY_tnt.WRKY47_col_a,young leaf,AT4G01720,GSM1925722_DAPSeq-WRKY_tnt-WRKY47_col_a-chr1-5...
2,GSM1925473,MYB_tnt.MYB77_col_a,young leaf,AT3G50060,GSM1925473_DAPSeq-MYB_tnt-MYB77_col_a-chr1-5_G...
3,GSM1925390,LOBAS2_tnt.LBD23_colamp_a,young leaf,AT3G26620,GSM1925390_DAPSeq-LOBAS2_tnt-LBD23_colamp_a-ch...
4,GSM1925261,C3H_tnt.At1g70910_col_a,young leaf,AT1G70910,GSM1925261_DAPSeq-C3H_tnt-At1g70910_col_a-chr1...

In [8]:
tar.extract(tarinfo)

In [9]:
f = tar.extractfile(tarinfo)

In [10]:
"DAPSeq" in tarinfo.name

True

In [11]:
narrowpeak_colums = [ #https://genome.ucsc.edu/FAQ/FAQformat.html#format12
    "chrom",       #Name of the chromosome (or contig, scaffold, etc.).
    "chromStart",  #The starting position of the feature in the chromosome or scaffold. The first base in a chromosome is numbered 0.
    "chromEnd",    #The ending position of the feature in the chromosome or scaffold. The chromEnd base is not included in the display of the feature. For example, the first 100 bases of a chromosome are defined as chromStart=0, chromEnd=100, and span the bases numbered 0-99.
    "name",        #Name given to a region (preferably unique). Use "." if no name is assigned.
    "score",       #Indicates how dark the peak will be displayed in the browser (0-1000). If all scores were "'0"' when the data were submitted to the DCC, the DCC assigned scores 1-1000 based on signal value. Ideally the average signalValue per base spread is between 100-1000.
    "strand",      #+/- to denote strand or orientation (whenever applicable). Use "." if no orientation is assigned.
    "signalValue", #Measurement of overall (usually, average) enrichment for the region.
    "pValue",      #Measurement of statistical significance (-log10). Use -1 if no pValue is assigned.
    "qValue",      #Measurement of statistical significance using false discovery rate (-log10). Use -1 if no qValue is assigned.
    "peak",        #Point-source called for this peak; 0-based offset from chromStart. Use -1 if no point-source called.
]
df = pd.read_csv(tar.extractfile(tarinfo), compression='gzip', sep='\t', header=None, names=narrowpeak_colums)

In [12]:
df.head()

,chrom,chromStart,chromEnd,name,score,strand,signalValue,pValue,qValue,peak
0,chr3,14192188,14192389,3:14192288,1000,.,102631.8,0.0,999.0,100
1,chr3,14194587,14194788,3:14194687,964,.,98541.2,0.0,999.0,100
2,chr3,14204356,14204557,3:14204456,914,.,92913.6,0.0,999.0,100
3,chr3,14204995,14205196,3:14205095,858,.,86452.7,0.0,999.0,100
4,chr2,1262,1463,2:1362,788,.,78560.6,0.0,999.0,100

In [13]:
df["chrom"] = df["chrom"].str.capitalize()
df.head()

,chrom,chromStart,chromEnd,name,score,strand,signalValue,pValue,qValue,peak
0,Chr3,14192188,14192389,3:14192288,1000,.,102631.8,0.0,999.0,100
1,Chr3,14194587,14194788,3:14194687,964,.,98541.2,0.0,999.0,100
2,Chr3,14204356,14204557,3:14204456,914,.,92913.6,0.0,999.0,100
3,Chr3,14204995,14205196,3:14205095,858,.,86452.7,0.0,999.0,100
4,Chr2,1262,1463,2:1362,788,.,78560.6,0.0,999.0,100

In [14]:
# BED columns
for x in df[["chrom", "chromStart", "chromEnd", "name"]].itertuples(index=False, name=None):
    print(x)
    break

('Chr3', 14192188, 14192389, '3:14192288')

In [15]:
from pybedtools import BedTool

In [16]:
# https://github.com/daler/pybedtools/issues/252
def is_valid_bedtools(a):
    '''Does not work for BedTool from iterable'''
    try:
        ft = a.file_type
        if ft == 'empty':
            print("empty file!")
        else:
            print(f'input is {ft} - OK!')
    except IndexError:
        print('bad input!')

In [100]:
tair_file = ref_data_dir / "Araport11_GFF3_genes_transposons.current_utf8_genes.gff.gz"
tair_gff = BedTool(tair_file)
is_valid_bedtools(tair_gff)
tair_gff = tair_gff.sort()
len(tair_gff)

input is gff - OK!

33243

In [30]:
dapseq_bed = BedTool.from_dataframe(df[["chrom", "chromStart", "chromEnd", "name"]])
dapseq_bed = dapseq_bed.sort()
is_valid_bedtools(dapseq_bed)
len(dapseq_bed)

input is bed - OK!

24762

In [20]:
dapseq_bed.head()

Chr1	6880	7081	1:6980
 Chr1	11625	11826	1:11725
 Chr1	12353	12554	1:12453
 Chr1	12788	12989	1:12888
 Chr1	20590	20791	1:20690
 Chr1	24765	24966	1:24865
 Chr1	33721	33922	1:33821
 Chr1	35295	35496	1:35395
 Chr1	42922	43123	1:43022
 Chr1	45352	45553	1:45452

In [101]:
# https://daler.github.io/pybedtools/autodocs/pybedtools.bedtool.BedTool.closest.html
# For each feature in A, finds the closest feature (upstream or downstream) in B.
# 's=False' ignore strand, 
# 'D=b' Report the closest feature in B, and its distance to A as an extra column. Use negative distances to report upstream features.
# Report distance with respect to B, when B is on the - strand, "upstream" means A has a higher (start,stop).
b = dapseq_bed.closest(tair_gff, s=False, D="b")
b.head(5)

Chr1	6880	7081	1:6980	Chr1	Araport11	gene	6788	9130	.	-	.	ID=AT1G01020;Name=AT1G01020;computational_description=ARV1 family protein;locus=2200940;locus_type=protein_coding;symbol=ARV1;Note=Arv1-like protein;Dbxref=TAIR:2200940;locus_type=protein_coding	0
 Chr1	11625	11826	1:11725	Chr1	Araport11	gene	11649	13714	.	-	.	ID=AT1G01030;Name=AT1G01030;full_name=NGATHA3;computational_description=AP2/B3-like transcriptional factor family protein;locus=2200950;locus_type=protein_coding;symbol=NGA3;Note=AP2/B3-like transcriptional factor family protein;Dbxref=TAIR:2200950;locus_type=protein_coding	0
 Chr1	12353	12554	1:12453	Chr1	Araport11	gene	11649	13714	.	-	.	ID=AT1G01030;Name=AT1G01030;full_name=NGATHA3;computational_description=AP2/B3-like transcriptional factor family protein;locus=2200950;locus_type=protein_coding;symbol=NGA3;Note=AP2/B3-like transcriptional factor family protein;Dbxref=TAIR:2200950;locus_type=protein_coding	0
 Chr1	12788	12989	1:12888	Chr1	Araport11	gene	11649	13714	.	-	.	ID=AT1G01030;Name=AT1G01030;full_name=NGATHA3;computational_description=AP2/B3-like transcriptional factor family protein;locus=2200950;locus_type=protein_coding;symbol=NGA3;Note=AP2/B3-like transcriptional factor family protein;Dbxref=TAIR:2200950;locus_type=protein_coding	0
 Chr1	20590	20791	1:20690	Chr1	Araport11	gene	23121	31227	.	+	.	ID=AT1G01040;Name=AT1G01040;full_name=dicer-like 1;computational_description=dicer-like 1;locus=2200960;locus_type=protein_coding;curator_summary=Encodes a Dicer homolog. Dicer is a RNA helicase involved in microRNA processing. Mutations in this locus can result in embryo lethality. Embryo shape at seed maturity is globular-elongate. Other mutants convert the floral meristems to an indeterminate state, others yet show defects in ovule development. mRNA is expressed in all shoot tissues. DCL1 is able to produce miRNAs and siRNAs. The mRNA is cell-to-cell mobile.;symbol=DCL1;Note=dicer-like 1;Dbxref=TAIR:2200960;locus_type=protein_coding	-2330

In [102]:
len(b)

25877

In [103]:
b.count()

25877

In [104]:
b.field_count()

14

In [105]:
# Intergenic peaks
# Report overlaps between two feature files. A.intersect(B)
# 'wo' Write the original A and B entries plus the number of base pairs of overlap between the two features. 
#      Overlaps restricted by -f and -r. Only A features with overlap are reported.
# 'F=' Minimum overlap required as a fraction of B.
intergenic_obj = dapseq_bed.intersect(tair_gff, wo=True)
intergenic_obj.head()

Chr1	6880	7081	1:6980	Chr1	Araport11	gene	6788	9130	.	-	.	ID=AT1G01020;Name=AT1G01020;computational_description=ARV1 family protein;locus=2200940;locus_type=protein_coding;symbol=ARV1;Note=Arv1-like protein;Dbxref=TAIR:2200940;locus_type=protein_coding	201
 Chr1	11625	11826	1:11725	Chr1	Araport11	gene	11649	13714	.	-	.	ID=AT1G01030;Name=AT1G01030;full_name=NGATHA3;computational_description=AP2/B3-like transcriptional factor family protein;locus=2200950;locus_type=protein_coding;symbol=NGA3;Note=AP2/B3-like transcriptional factor family protein;Dbxref=TAIR:2200950;locus_type=protein_coding	178
 Chr1	12353	12554	1:12453	Chr1	Araport11	gene	11649	13714	.	-	.	ID=AT1G01030;Name=AT1G01030;full_name=NGATHA3;computational_description=AP2/B3-like transcriptional factor family protein;locus=2200950;locus_type=protein_coding;symbol=NGA3;Note=AP2/B3-like transcriptional factor family protein;Dbxref=TAIR:2200950;locus_type=protein_coding	201
 Chr1	12788	12989	1:12888	Chr1	Araport11	gene	11649	13714	.	-	.	ID=AT1G01030;Name=AT1G01030;full_name=NGATHA3;computational_description=AP2/B3-like transcriptional factor family protein;locus=2200950;locus_type=protein_coding;symbol=NGA3;Note=AP2/B3-like transcriptional factor family protein;Dbxref=TAIR:2200950;locus_type=protein_coding	201
 Chr1	24765	24966	1:24865	Chr1	Araport11	gene	23121	31227	.	+	.	ID=AT1G01040;Name=AT1G01040;full_name=dicer-like 1;computational_description=dicer-like 1;locus=2200960;locus_type=protein_coding;curator_summary=Encodes a Dicer homolog. Dicer is a RNA helicase involved in microRNA processing. Mutations in this locus can result in embryo lethality. Embryo shape at seed maturity is globular-elongate. Other mutants convert the floral meristems to an indeterminate state, others yet show defects in ovule development. mRNA is expressed in all shoot tissues. DCL1 is able to produce miRNAs and siRNAs. The mRNA is cell-to-cell mobile.;symbol=DCL1;Note=dicer-like 1;Dbxref=TAIR:2200960;locus_type=protein_coding	201
 Chr1	33721	33922	1:33821	Chr1	Araport11	gene	33365	37871	.	-	.	ID=AT1G01060;Name=AT1G01060;full_name=LATE ELONGATED HYPOCOTYL;computational_description=Homeodomain-like superfamily protein;locus=2200970;locus_type=protein_coding;curator_summary=LHY encodes a myb-related putative transcription factor involved in circadian rhythm along with another myb transcription factor CCA1;symbol=LHY;Note=Homeodomain-like superfamily protein;Dbxref=TAIR:2200970;locus_type=protein_coding	201
 Chr1	35295	35496	1:35395	Chr1	Araport11	gene	33365	37871	.	-	.	ID=AT1G01060;Name=AT1G01060;full_name=LATE ELONGATED HYPOCOTYL;computational_description=Homeodomain-like superfamily protein;locus=2200970;locus_type=protein_coding;curator_summary=LHY encodes a myb-related putative transcription factor involved in circadian rhythm along with another myb transcription factor CCA1;symbol=LHY;Note=Homeodomain-like superfamily protein;Dbxref=TAIR:2200970;locus_type=protein_coding	201
 Chr1	42922	43123	1:43022	Chr1	Araport11	gene	43087	43295	.	-	.	ID=AT1G04003;Name=AT1G04003;locus_type=long_noncoding_rna	37
 Chr1	45352	45553	1:45452	Chr1	Araport11	gene	44970	47059	.	-	.	ID=AT1G01080;Name=AT1G01080;Dbxref=TAIR:2200975;locus_type=protein_coding	201
 Chr1	45722	45923	1:45822	Chr1	Araport11	gene	44970	47059	.	-	.	ID=AT1G01080;Name=AT1G01080;Dbxref=TAIR:2200975;locus_type=protein_coding	201

In [106]:
intergenic_obj.file_type

'bed'

In [107]:
len(intergenic_obj)

18280

In [ ]:
# Questions 
# - remove peaks within genes?
# GSM1466341_ChIPSeq-ABI5_Ab.chr1-5_macs02_peaks.narrowPeak.gz
# Refine definition of TSS? https://www.arabidopsis.org/portals/genAnnotation/genome_annotation_tools/cis_element.jsp